name: Build master

on:
  push:
    branches: [ ci-rework ]
  pull_request:
    branches: [ ci-rework ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies-composite-action

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_ALL_TOOLS=Yes -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build -j

  lint:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies-composite-action

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_ALL_TOOLS=Yes -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: 'build'
          ignore: 'QML|data|.github|build|Engine/3rdparty|Engine/shaders'
          style: 'file'
          tidy-checks: ''
          files-changed-only: false
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Check failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
