name: Build master

on:
  push:
    paths-ignore:
      - README.md
      # do not run CI if we are writing a paper
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
    branches:
      - 'master'
  #schedule:
  #  - cron: "0 13 * * 1"
    # https://jasonet.co/posts/scheduled-actions/

jobs:
  build:
    #env:
      #OCANREN_STATS: yes
      # enabling stats required extra link library

    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.0
      #   with:
      #     access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - run: sudo apt update -y

      - name: Install dependencies via APT
        run: |
          sudo apt install -y libboost-iostreams1.83-dev libjpeg-dev liblzma-dev libjsoncpp-dev python3-dev libfreetype6-dev libboost-system-dev libboost-thread-dev libboost-python-dev  libsdl2-mixer-dev libsdl2-dev cmake libopenal-dev \
           qt5-qmake qtdeclarative5-dev

      - name: Run cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j

